/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_trimble_outdoors_ndk_parcelinfo_ParcelUtils */

#ifndef _Included_com_trimble_outdoors_ndk_parcelinfo_ParcelUtils
#define _Included_com_trimble_outdoors_ndk_parcelinfo_ParcelUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_trimble_outdoors_ndk_parcelinfo_ParcelUtils
 * Method:    getParcelInfo
 * Signature: (Ljava/lang/String;Lcom/trimble/outdoors/ndk/parcelinfo/ParcelUtils/Point;)Lcom/trimble/outdoors/ndk/parcelinfo/ParcelUtils/ParcelInfo;
 */
JNIEXPORT jobject JNICALL Java_com_trimble_outdoors_ndk_parcelinfo_ParcelUtils_getParcelInfo
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
