/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_trimble_outdoors_ndk_parcelinfo_ParcelUtils_Ring */

#ifndef _Included_com_trimble_outdoors_ndk_parcelinfo_ParcelUtils_Ring
#define _Included_com_trimble_outdoors_ndk_parcelinfo_ParcelUtils_Ring
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
